project: phone
listen: 3006

rabbit:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

sms:
  -
    codes: []
    enable: true
    settings:
      url: 'https://www.smsdirect.ru/submit_message'
      login: login
      password: password
      from: FROM
    transport: SmsDirect